{
    "sourceFile": "node_modules/next/dist/client/components/react-dev-overlay/utils/get-error-by-type.js",
    "activeCommit": 0,
    "commits": [
        {
            "activePatchIndex": 0,
            "patches": [
                {
                    "date": 1746892688731,
                    "content": "Index: \n===================================================================\n--- \n+++ \n"
                }
            ],
            "date": 1746891704042,
            "name": "cart",
            "content": "\"use strict\";\nObject.defineProperty(exports, \"__esModule\", {\n    value: true\n});\n0 && (module.exports = {\n    getErrorByType: null,\n    useFrames: null\n});\nfunction _export(target, all) {\n    for(var name in all)Object.defineProperty(target, name, {\n        enumerable: true,\n        get: all[name]\n    });\n}\n_export(exports, {\n    getErrorByType: function() {\n        return getErrorByType;\n    },\n    useFrames: function() {\n        return useFrames;\n    }\n});\nconst _interop_require_default = require(\"@swc/helpers/_/_interop_require_default\");\nconst _shared = require(\"../shared\");\nconst _stackframe = require(\"./stack-frame\");\nconst _errorsource = require(\"../../../../shared/lib/error-source\");\nconst _react = /*#__PURE__*/ _interop_require_default._(require(\"react\"));\nconst useFrames = (error)=>{\n    if ('use' in _react.default) {\n        const frames = error.frames;\n        if (typeof frames !== 'function') {\n            throw Object.defineProperty(new Error('Invariant: frames must be a function when the React version has React.use. This is a bug in Next.js.'), \"__NEXT_ERROR_CODE\", {\n                value: \"E636\",\n                enumerable: false,\n                configurable: true\n            });\n        }\n        return _react.default.use(frames());\n    } else {\n        if (!Array.isArray(error.frames)) {\n            throw Object.defineProperty(new Error('Invariant: frames must be an array when the React version does not have React.use. This is a bug in Next.js.'), \"__NEXT_ERROR_CODE\", {\n                value: \"E637\",\n                enumerable: false,\n                configurable: true\n            });\n        }\n        return error.frames;\n    }\n};\nasync function getErrorByType(ev, isAppDir) {\n    const { id, event } = ev;\n    switch(event.type){\n        case _shared.ACTION_UNHANDLED_ERROR:\n        case _shared.ACTION_UNHANDLED_REJECTION:\n            {\n                const baseError = {\n                    id,\n                    runtime: true,\n                    error: event.reason\n                };\n                if ('use' in _react.default) {\n                    const readyRuntimeError = {\n                        ...baseError,\n                        // createMemoizedPromise dedups calls to getOriginalStackFrames\n                        frames: createMemoizedPromise(async ()=>{\n                            return await (0, _stackframe.getOriginalStackFrames)(event.frames, (0, _errorsource.getErrorSource)(event.reason), isAppDir);\n                        })\n                    };\n                    if (event.type === _shared.ACTION_UNHANDLED_ERROR) {\n                        readyRuntimeError.componentStackFrames = event.componentStackFrames;\n                    }\n                    return readyRuntimeError;\n                } else {\n                    const readyRuntimeError = {\n                        ...baseError,\n                        // createMemoizedPromise dedups calls to getOriginalStackFrames\n                        frames: await (0, _stackframe.getOriginalStackFrames)(event.frames, (0, _errorsource.getErrorSource)(event.reason), isAppDir)\n                    };\n                    if (event.type === _shared.ACTION_UNHANDLED_ERROR) {\n                        readyRuntimeError.componentStackFrames = event.componentStackFrames;\n                    }\n                    return readyRuntimeError;\n                }\n            }\n        default:\n            {\n                break;\n            }\n    }\n    // eslint-disable-next-line @typescript-eslint/no-unused-vars\n    const _ = event;\n    throw Object.defineProperty(new Error('type system invariant violation'), \"__NEXT_ERROR_CODE\", {\n        value: \"E335\",\n        enumerable: false,\n        configurable: true\n    });\n}\nfunction createMemoizedPromise(promiseFactory) {\n    const cachedPromise = promiseFactory();\n    return function() {\n        return cachedPromise;\n    };\n}\n\nif ((typeof exports.default === 'function' || (typeof exports.default === 'object' && exports.default !== null)) && typeof exports.default.__esModule === 'undefined') {\n  Object.defineProperty(exports.default, '__esModule', { value: true });\n  Object.assign(exports.default, exports);\n  module.exports = exports.default;\n}\n\n//# sourceMappingURL=get-error-by-type.js.map"
        }
    ]
}